version: '3.8'
services:
  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  book-store-app:
    build: .
    container_name: book-store-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
